version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      python-development-dependencies:
        dependency-type: development
  - package-ecosystem: pip
    directory: "/20_SRC/infra"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
